### PR TITLE
mostly travis-ci stuff

### PR DESCRIPTION
**Pull request by danikp**
a fix of #199 
* create plt faster with minimal number of apps required
* dialyzer analysis logs are more verbose

requires erlydtl/merl#3 to work properly

### CODE REVIEW

**Comment by kaos** [comment]
Ok, thanks. This looks much better!

Two things: I don't want to merge this while the travis build fails (as it would mask any issues in the unit tests), and could you please squash the history to a single commit would be great.

**Comment by danikp** [comment]
I did a first part, logs are shown, but exit value is ignored. But not sure if there is a way to squash commits into single one without dropping this PR and creating new one from freshly created branch.

**Comment by kaos** [comment]
@danikp `git rebase -i && git push -f` 

i.e. you simply push to the same branch as you normally do to add commits, but with a forced push you can rewrite the entire history for the branch, the PR will keep track of it. ;)

**Comment by danikp** [comment]
@kaos, that code was already there, tried not to change too much. From dialyzer help 

The exit status of the command line version is:
  0 - No problems were encountered during the analysis and no
      warnings were emitted.
  1 - Problems were encountered during the analysis.
  2 - No problems were encountered, but warnings were emitted.

**Comment by kaos** [comment]
Ah, ok. That's good then. Thanks.

**Comment by kaos** [comment]
Merged. Notice that I cleaned up the history for you, so you may want to keep an eye on that when you pull from erlydtl/master (as I see you made all these changes on your master..).

**Comment by danikp** [comment]
Thanks, looks really good now.

**Pull request closed without merging**
