### PR TITLE
Fix stacktrace warnings

### PR DESCRIPTION
**Pull request by burbas**
I'm not 100% sure you want to include the erlydtl_ext.hrl in erlydtl_ext.hrl but it was either that, have a separate hrl-file or duplicated code. Think this is the least evil thing :-).

### CODE REVIEW

**Comment by burbas** [comment]
Travis failed cause an internal problem with fetching R15B03 .

**Comment by seriyps** [comment]
Looks good for me

**Comment by seriyps** [comment]
Regarding OTP15 - maybe we should just drop it from .travis.yml? It's too old. Would you mind creating a separate PR or maybe just add to this one?

**Comment by burbas** [comment]
I can add to this one.

**Comment by seriyps** [comment]
Let's see if @kaos has some feedback. Otherwise will merge, let's say, this Friday.

**Comment by kaos** [comment]
LGTM. Thank you for the contribution.

**Pull request merged**
