### PR TITLE
update rebar.config to accept version 18.*

### PR DESCRIPTION
**Pull request by ricecake**

### CODE REVIEW

**Comment by kaos** [comment]
Thanks. I'd like to also update the .tavis.yml file at the same time.

https://github.com/erlydtl/erlydtl/blob/master/.travis.yml#L3

**Comment by ricecake** [comment]
Sorry 'bout the delay, somehow missed the notification about your comment.

**Comment by kaos** [comment]
Thanks. Will have to look into the one failing test before merging, though. Unless someone else beats me to it.

**Comment by roowe** [comment]
%% test/erlydtl_eunit_testrunner.erl:45:in `erlydtl_eunit_testrunner:run_test/1`
     Output: :588: Warning: a term is constructed, but never used

     Output: :588: Warning: a term is constructed, but never used

please fix it, thx

**Comment by kaos** [comment]
@ricecake no worries. Thanks for the pull request.

@roowe fixed ;)

I just realize that if you compile your templates with warnings on, and you use the extends tag and have overridden blocks without referencing their contents with `{{ block.super }}`, you'll get this warning too.. just a heads up..

**Comment by roowe** [comment]
@kaos thx

**Pull request merged**
